"""add objectives and evaluations

Revision ID: 0b9fe28e7e3b
Revises: 8a2e5808f5cf
Create Date: 2026-06-26 18:35:59.816479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9fe28e7e3b'
down_revision = '8a2e5808f5cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('period_year', sa.SmallInteger(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('objective_deadline', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("period_type IN ('annual','semester','quarterly','probation','custom')", name='ck_campaigns_period_type_valid'),
    sa.CheckConstraint('end_date >= start_date', name='ck_campaigns_end_after_start'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_campaigns', schema=None) as batch_op:
        batch_op.create_index('ix_campaigns_active', ['company_id', 'is_active'], unique=False)
        batch_op.create_index('ix_campaigns_company_id', ['company_id'], unique=False)

    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('manager_overall_comment', sa.Text(), nullable=True),
    sa.Column('employee_overall_comment', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('areas_for_improvement', sa.Text(), nullable=True),
    sa.Column('development_plan', sa.Text(), nullable=True, comment='Plan de Développement Individuel (PDI)'),
    sa.Column('sent_to_evaluator_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evaluator_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_to_employee_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('employee_acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('employee_signature_hash', sa.String(length=255), nullable=True),
    sa.Column('manager_signature_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft','in_progress','employee_review','completed','archived')", name='ck_evaluations_status_valid'),
    sa.CheckConstraint('employee_id <> evaluator_id', name='ck_evaluations_employee_differs_evaluator'),
    sa.CheckConstraint('overall_score IS NULL OR overall_score BETWEEN 0 AND 5', name='ck_evaluations_score_valid'),
    sa.ForeignKeyConstraint(['campaign_id'], ['evaluation_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluator_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'employee_id', name='uq_evaluations_campaign_employee')
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index('ix_evaluations_campaign_id', ['campaign_id'], unique=False)
        batch_op.create_index('ix_evaluations_employee_id', ['employee_id'], unique=False)
        batch_op.create_index('ix_evaluations_evaluator_id', ['evaluator_id'], unique=False)
        batch_op.create_index('ix_evaluations_status', ['status'], unique=False)

    op.create_table('objectives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('set_by_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('success_criteria', sa.Text(), nullable=True, comment='Critères mesurables de réussite (logique SMART)'),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False, comment="Pondération de l'objectif dans l'évaluation globale (%)"),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completion_pct', sa.SmallInteger(), nullable=False),
    sa.Column('manager_rating', sa.SmallInteger(), nullable=True),
    sa.Column('employee_rating', sa.SmallInteger(), nullable=True),
    sa.Column('manager_comment', sa.Text(), nullable=True),
    sa.Column('employee_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft','active','completed','cancelled','overdue')", name='ck_objectives_status_valid'),
    sa.CheckConstraint('completion_pct BETWEEN 0 AND 100', name='ck_objectives_completion_valid'),
    sa.CheckConstraint('employee_id <> set_by_id', name='ck_objectives_employee_differs_setter'),
    sa.CheckConstraint('employee_rating IS NULL OR employee_rating BETWEEN 1 AND 5', name='ck_objectives_employee_rating_valid'),
    sa.CheckConstraint('manager_rating IS NULL OR manager_rating BETWEEN 1 AND 5', name='ck_objectives_manager_rating_valid'),
    sa.CheckConstraint('weight > 0 AND weight <= 100', name='ck_objectives_weight_valid'),
    sa.ForeignKeyConstraint(['campaign_id'], ['evaluation_campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_by_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.create_index('ix_objectives_campaign_id', ['campaign_id'], unique=False)
        batch_op.create_index('ix_objectives_due_date', ['due_date'], unique=False)
        batch_op.create_index('ix_objectives_employee_id', ['employee_id'], unique=False)
        batch_op.create_index('ix_objectives_status', ['status'], unique=False)

    op.create_table('evaluation_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('manager_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('employee_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('manager_comment', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('employee_score IS NULL OR employee_score BETWEEN 0 AND 5', name='ck_evaluation_items_employee_score_valid'),
    sa.CheckConstraint('manager_score IS NULL OR manager_score BETWEEN 0 AND 5', name='ck_evaluation_items_manager_score_valid'),
    sa.CheckConstraint('weight > 0', name='ck_evaluation_items_weight_positive'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_items', schema=None) as batch_op:
        batch_op.create_index('ix_evaluation_items_evaluation_id', ['evaluation_id'], unique=False)

    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation_items', schema=None) as batch_op:
        batch_op.drop_index('ix_evaluation_items_evaluation_id')

    op.drop_table('evaluation_items')
    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.drop_index('ix_objectives_status')
        batch_op.drop_index('ix_objectives_employee_id')
        batch_op.drop_index('ix_objectives_due_date')
        batch_op.drop_index('ix_objectives_campaign_id')

    op.drop_table('objectives')
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index('ix_evaluations_status')
        batch_op.drop_index('ix_evaluations_evaluator_id')
        batch_op.drop_index('ix_evaluations_employee_id')
        batch_op.drop_index('ix_evaluations_campaign_id')

    op.drop_table('evaluations')
    with op.batch_alter_table('evaluation_campaigns', schema=None) as batch_op:
        batch_op.drop_index('ix_campaigns_company_id')
        batch_op.drop_index('ix_campaigns_active')

    op.drop_table('evaluation_campaigns')
    # ### end Alembic commands ###
