"""add recruitment tables

Revision ID: 75608117b219
Revises: 94f5ce7cb17a
Create Date: 2026-06-29 23:33:24.378589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75608117b219'
down_revision = '94f5ce7cb17a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email du candidat — identifiant naturel pour la déduplication'),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('cv_path', sa.String(length=500), nullable=True, comment='Chemin relatif vers le fichier CV (PDF, DOCX…)'),
    sa.Column('cv_text', sa.Text(), nullable=True, comment='Texte brut du CV (copié-collé ou extrait)'),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notes internes RH (non visibles par le candidat)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('linkedin','jobboard','referral','spontaneous','website','other')", name='ck_candidates_source_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index('ix_candidates_email', ['email'], unique=False)
        batch_op.create_index('ix_candidates_last_name', ['last_name'], unique=False)

    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='Département qui recrute'),
    sa.Column('position_id', sa.Integer(), nullable=True, comment='Poste cible dans le référentiel RH'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment="Utilisateur ayant créé l'offre (RH ou Admin)"),
    sa.Column('title', sa.String(length=200), nullable=False, comment="Intitulé du poste tel qu'affiché aux candidats"),
    sa.Column('description', sa.Text(), nullable=True, comment='Description complète du poste, missions, profil recherché'),
    sa.Column('requirements', sa.Text(), nullable=True, comment='Compétences et qualifications requises'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='Lieu de travail (ville, télétravail…)'),
    sa.Column('contract_type', sa.String(length=50), nullable=True, comment='Type de contrat proposé (CDI, CDD, stage, alternance…)'),
    sa.Column('salary_min', sa.Numeric(precision=10, scale=2), nullable=True, comment='Fourchette salariale basse (brut annuel €)'),
    sa.Column('salary_max', sa.Numeric(precision=10, scale=2), nullable=True, comment='Fourchette salariale haute (brut annuel €)'),
    sa.Column('headcount', sa.Integer(), nullable=True, comment='Nombre de postes à pourvoir'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('closing_date', sa.Date(), nullable=True, comment='Date limite de dépôt des candidatures'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft','open','closed','cancelled')", name='ck_job_postings_status_valid'),
    sa.CheckConstraint('closing_date IS NULL OR published_at IS NULL OR closing_date >= published_at', name='ck_job_postings_closing_after_publish'),
    sa.CheckConstraint('headcount IS NULL OR headcount > 0', name='ck_job_postings_headcount_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.create_index('ix_job_postings_company_id', ['company_id'], unique=False)
        batch_op.create_index('ix_job_postings_department_id', ['department_id'], unique=False)
        batch_op.create_index('ix_job_postings_status', ['company_id', 'status'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('hired_employee_id', sa.Integer(), nullable=True, comment="Fiche employé créée à l'issue du recrutement — NULL jusqu'à sa création"),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False, comment='Date effective de soumission de la candidature'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Notes RH internes sur cette candidature'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='Motif de refus (communication possible au candidat)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('recue','preselectionnee','entretien','offre','refusee','embauchee')", name='ck_applications_status_valid'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hired_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'job_posting_id', name='uq_applications_candidate_per_posting')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index('ix_applications_candidate_id', ['candidate_id'], unique=False)
        batch_op.create_index('ix_applications_hired_employee_id', ['hired_employee_id'], unique=False)
        batch_op.create_index('ix_applications_job_posting_id', ['job_posting_id'], unique=False)
        batch_op.create_index('ix_applications_status', ['job_posting_id', 'status'], unique=False)

    op.create_table('interviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('interviewer_id', sa.Integer(), nullable=True, comment="Employé qui conduit l'entretien"),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False, comment="Date et heure planifiées de l'entretien"),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='Durée prévue en minutes'),
    sa.Column('location', sa.String(length=300), nullable=True, comment='Lieu (salle, lien de visioconférence…)'),
    sa.Column('interview_type', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True, comment="Notes et observations de l'interviewer pendant l'entretien"),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True, comment='Note globale du candidat sur 5 (1 = insuffisant, 5 = excellent)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision IN ('pending','proceed','hold','reject')", name='ck_interviews_decision_valid'),
    sa.CheckConstraint("interview_type IN ('phone','video','onsite','technical','hr')", name='ck_interviews_type_valid'),
    sa.CheckConstraint('duration_minutes IS NULL OR duration_minutes > 0', name='ck_interviews_duration_positive'),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 5)', name='ck_interviews_rating_range'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interviewer_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.create_index('ix_interviews_application_id', ['application_id'], unique=False)
        batch_op.create_index('ix_interviews_interviewer_id', ['interviewer_id'], unique=False)
        batch_op.create_index('ix_interviews_scheduled_at', ['scheduled_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_index('ix_interviews_scheduled_at')
        batch_op.drop_index('ix_interviews_interviewer_id')
        batch_op.drop_index('ix_interviews_application_id')

    op.drop_table('interviews')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index('ix_applications_status')
        batch_op.drop_index('ix_applications_job_posting_id')
        batch_op.drop_index('ix_applications_hired_employee_id')
        batch_op.drop_index('ix_applications_candidate_id')

    op.drop_table('applications')
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_index('ix_job_postings_status')
        batch_op.drop_index('ix_job_postings_department_id')
        batch_op.drop_index('ix_job_postings_company_id')

    op.drop_table('job_postings')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index('ix_candidates_last_name')
        batch_op.drop_index('ix_candidates_email')

    op.drop_table('candidates')
    # ### end Alembic commands ###
