"""add contract_types and contracts

Revision ID: 8a2e5808f5cf
Revises: b3a59cf060e8
Create Date: 2026-06-24 10:41:30.293833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a2e5808f5cf'
down_revision = 'b3a59cf060e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('duration_type', sa.String(length=20), nullable=False),
    sa.Column('paid_leave_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rtt_days', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('notice_period_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("duration_type IN ('cdi','cdd','interim','apprenticeship','internship','freelance')", name='ck_contract_types_duration_valid'),
    sa.CheckConstraint('notice_period_days >= 0', name='ck_contract_types_notice_positive'),
    sa.CheckConstraint('paid_leave_days >= 0', name='ck_contract_types_leave_positive'),
    sa.CheckConstraint('rtt_days >= 0', name='ck_contract_types_rtt_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_contract_types_name_per_company')
    )
    with op.batch_alter_table('contract_types', schema=None) as batch_op:
        batch_op.create_index('ix_contract_types_company_id', ['company_id'], unique=False)

    op.create_table('contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('contract_type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True, comment='NULL = CDI ou contrat sans terme défini'),
    sa.Column('trial_end_date', sa.Date(), nullable=True),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('weekly_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('document_path', sa.String(length=500), nullable=True, comment='Contrat signé numérisé'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR end_date > start_date', name='ck_contracts_end_after_start'),
    sa.CheckConstraint('gross_salary > 0', name='ck_contracts_salary_positive'),
    sa.CheckConstraint('trial_end_date IS NULL OR trial_end_date >= start_date', name='ck_contracts_trial_after_start'),
    sa.CheckConstraint('weekly_hours > 0 AND weekly_hours <= 48', name='ck_contracts_hours_valid'),
    sa.ForeignKeyConstraint(['contract_type_id'], ['contract_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index('ix_contracts_employee_current', ['employee_id', 'is_current'], unique=False)
        batch_op.create_index('ix_contracts_employee_id', ['employee_id'], unique=False)
        batch_op.create_index('ix_contracts_end_date', ['end_date'], unique=False)

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index('ix_contracts_end_date')
        batch_op.drop_index('ix_contracts_employee_id')
        batch_op.drop_index('ix_contracts_employee_current')

    op.drop_table('contracts')
    with op.batch_alter_table('contract_types', schema=None) as batch_op:
        batch_op.drop_index('ix_contract_types_company_id')

    op.drop_table('contract_types')
    # ### end Alembic commands ###
