"""add trainings and enrollments tables

Revision ID: 94f5ce7cb17a
Revises: de14911a2800
Create Date: 2026-06-29 22:28:03.052427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f5ce7cb17a'
down_revision = 'de14911a2800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True, comment='NULL = formation partagée entre entreprises / catalogue global'),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organisme', sa.String(length=200), nullable=True, comment="Nom de l'organisme ou du prestataire de formation"),
    sa.Column('duration_hours', sa.Numeric(precision=6, scale=2), nullable=True, comment='Durée totale en heures (décimales acceptées)'),
    sa.Column('training_type', sa.String(length=20), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True, comment='Coût unitaire par participant en euros HT'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("training_type IN ('presentiel','distanciel','e_learning')", name='ck_trainings_type_valid'),
    sa.CheckConstraint('cost IS NULL OR cost >= 0', name='ck_trainings_cost_non_negative'),
    sa.CheckConstraint('duration_hours IS NULL OR duration_hours > 0', name='ck_trainings_duration_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.create_index('ix_trainings_active', ['company_id', 'is_active'], unique=False)
        batch_op.create_index('ix_trainings_company_id', ['company_id'], unique=False)

    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True, comment='Note finale sur 100'),
    sa.Column('final_comment', sa.Text(), nullable=True, comment='Appréciation qualitative issue de la formation'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('planifiee','en_cours','terminee','annulee')", name='ck_enrollments_status_valid'),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name='ck_enrollments_end_after_start'),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 100)', name='ck_enrollments_score_range'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index('ix_enrollments_employee_id', ['employee_id'], unique=False)
        batch_op.create_index('ix_enrollments_employee_status', ['employee_id', 'status'], unique=False)
        batch_op.create_index('ix_enrollments_status', ['status'], unique=False)
        batch_op.create_index('ix_enrollments_training_id', ['training_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index('ix_enrollments_training_id')
        batch_op.drop_index('ix_enrollments_status')
        batch_op.drop_index('ix_enrollments_employee_status')
        batch_op.drop_index('ix_enrollments_employee_id')

    op.drop_table('enrollments')
    with op.batch_alter_table('trainings', schema=None) as batch_op:
        batch_op.drop_index('ix_trainings_company_id')
        batch_op.drop_index('ix_trainings_active')

    op.drop_table('trainings')
    # ### end Alembic commands ###
