"""initial schema: auth, organization, employee, leave, calendar, audit, notification

Revision ID: b3a59cf060e8
Revises: 
Create Date: 2026-06-22 12:12:50.711521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3a59cf060e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('siret', sa.String(length=14), nullable=True),
    sa.Column('naf_code', sa.String(length=10), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('fiscal_year_start', sa.SmallInteger(), nullable=False, comment="Mois de début d'exercice fiscal (1=janvier ... 12=décembre)"),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('fiscal_year_start BETWEEN 1 AND 12', name='ck_companies_fiscal_year_start_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('siret', name='uq_companies_siret')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True, comment='Employé responsable du département'),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True, comment="Code court (ex: 'TECH', 'RH', 'FIN')"),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost_center', sa.String(length=50), nullable=True, comment='Centre de coût analytique'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id <> parent_id', name='ck_departments_no_self_parent'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_departments_name_per_company')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index('ix_departments_company_id', ['company_id'], unique=False)
        batch_op.create_index('ix_departments_manager_id', ['manager_id'], unique=False)
        batch_op.create_index('ix_departments_parent_id', ['parent_id'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False, comment='Identifiant public non séquentiel (API, URLs)'),
    sa.Column('employee_number', sa.String(length=50), nullable=True, comment='Matricule RH'),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('maiden_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_place', sa.String(length=150), nullable=True),
    sa.Column('nationality', sa.String(length=2), nullable=True),
    sa.Column('national_id_number', sa.String(length=255), nullable=True, comment='Numéro de sécurité sociale — CHIFFRÉ côté application avant stockage'),
    sa.Column('personal_email', sa.String(length=255), nullable=True),
    sa.Column('personal_phone', sa.String(length=30), nullable=True),
    sa.Column('professional_phone', sa.String(length=30), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('emergency_contact_relationship', sa.String(length=50), nullable=True),
    sa.Column('iban', sa.String(length=255), nullable=True, comment='Chiffré côté application (AES-256)'),
    sa.Column('bic', sa.String(length=255), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('termination_reason', sa.Text(), nullable=True),
    sa.Column('probation_end_date', sa.Date(), nullable=True),
    sa.Column('annual_gross_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True, comment="Notes internes RH — non visibles par l'employé"),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("gender IS NULL OR gender IN ('male','female','other','prefer_not_to_say')", name='ck_employees_gender_valid'),
    sa.CheckConstraint("status IN ('active','on_leave','probation','terminated','suspended')", name='ck_employees_status_valid'),
    sa.CheckConstraint('annual_gross_salary IS NULL OR annual_gross_salary > 0', name='ck_employees_salary_positive'),
    sa.CheckConstraint('id <> manager_id', name='ck_employees_no_self_manager'),
    sa.CheckConstraint('probation_end_date IS NULL OR probation_end_date >= hire_date', name='ck_employees_probation_after_hire'),
    sa.CheckConstraint('termination_date IS NULL OR termination_date >= hire_date', name='ck_employees_termination_after_hire'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ondelete='SET NULL'),
    
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_number', name='uq_employees_employee_number'),
    sa.UniqueConstraint('user_id', name='uq_employees_user_id'),
    sa.UniqueConstraint('uuid', name='uq_employees_uuid')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index('ix_employees_company_status', ['company_id', 'status'], unique=False)
        batch_op.create_index('ix_employees_department_id', ['department_id'], unique=False)
        batch_op.create_index('ix_employees_manager_id', ['manager_id'], unique=False)
        batch_op.create_index('ix_employees_name', ['last_name', 'first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_uuid'), ['uuid'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_permission_code')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=True, comment='Niveau hiérarchique : junior, intermediate, senior, lead, manager, director, executive'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("level IS NULL OR level IN ('junior','intermediate','senior','lead','manager','director','executive')", name='ck_positions_level_valid'),
    sa.CheckConstraint('min_salary IS NULL OR max_salary IS NULL OR min_salary <= max_salary', name='ck_positions_salary_range_valid'),
    
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'title', name='uq_positions_title_per_department')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index('ix_positions_department_id', ['department_id'], unique=False)
        batch_op.create_index('ix_positions_level', ['level'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment="TRUE = rôle non modifiable ni supprimable via l'interface"),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='uq_role_name')
    )
    op.create_table('leave_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='Code court stable (CP, RTT, MAL...)'),
    sa.Column('color_hex', sa.String(length=7), nullable=False, comment="Couleur d'affichage calendrier (format #RRGGBB)"),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requires_justification', sa.Boolean(), nullable=False, comment='Un commentaire/motif est obligatoire à la demande'),
    sa.Column('requires_document', sa.Boolean(), nullable=False, comment='Un justificatif (PJ) est obligatoire (ex : arrêt maladie)'),
    sa.Column('max_consecutive_days', sa.Integer(), nullable=True, comment='Limite de jours consécutifs (NULL = illimité)'),
    sa.Column('min_advance_notice_days', sa.Integer(), nullable=False, comment='Délai de prévenance minimum avant la date de début'),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('impacts_leave_balance', sa.Boolean(), nullable=False, comment="True = décompte un solde (CP, RTT) ; False = n'en consomme pas (maladie)"),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_consecutive_days IS NULL OR max_consecutive_days > 0', name='ck_leave_types_max_days_positive'),
    sa.CheckConstraint('min_advance_notice_days >= 0', name='ck_leave_types_notice_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_leave_types_code_per_company'),
    sa.UniqueConstraint('company_id', 'name', name='uq_leave_types_name_per_company')
    )
    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.create_index('ix_leave_types_active', ['company_id', 'is_active'], unique=False)
        batch_op.create_index('ix_leave_types_company_id', ['company_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_sites_name_per_company')
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index('ix_sites_company_id', ['company_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False, comment='Identifiant public non séquentiel (URLs, API)'),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('force_password_change', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True, comment='Secret base32 — chiffré côté application avant stockage'),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True, comment='Supporte IPv4 et IPv6'),
    sa.Column('failed_login_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='NULL = compte non verrouillé'),
    sa.Column('preferred_language', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("email ~* '^[A-Za-z0-9._%%+\\-]+@[A-Za-z0-9.\\-]+\\.[A-Za-z]{2,}$'", name='ck_users_email_format'),
    sa.CheckConstraint('failed_login_attempts >= 0', name='ck_users_attempts_positive'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_active', ['is_active'], unique=False)
        batch_op.create_index('ix_users_email_lower', ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_uuid'), ['uuid'], unique=True)

    op.create_table('work_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('monday_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('tuesday_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('wednesday_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('thursday_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('friday_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('saturday_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('sunday_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('friday_hours >= 0', name='ck_work_schedules_friday_positive'),
    sa.CheckConstraint('monday_hours >= 0', name='ck_work_schedules_monday_positive'),
    sa.CheckConstraint('saturday_hours >= 0', name='ck_work_schedules_saturday_positive'),
    sa.CheckConstraint('sunday_hours >= 0', name='ck_work_schedules_sunday_positive'),
    sa.CheckConstraint('thursday_hours >= 0', name='ck_work_schedules_thursday_positive'),
    sa.CheckConstraint('tuesday_hours >= 0', name='ck_work_schedules_tuesday_positive'),
    sa.CheckConstraint('wednesday_hours >= 0', name='ck_work_schedules_wednesday_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_work_schedules_name_per_company')
    )
    with op.batch_alter_table('work_schedules', schema=None) as batch_op:
        batch_op.create_index('ix_work_schedules_company_id', ['company_id'], unique=False)

    op.create_table('leave_balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('carried_over', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('acquired', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('taken', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('pending', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('adjustment', sa.Numeric(precision=6, scale=2), nullable=False, comment='Correction manuelle RH — peut être négative'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('acquired >= 0', name='ck_leave_balances_acquired_positive'),
    sa.CheckConstraint('carried_over >= 0', name='ck_leave_balances_carried_positive'),
    sa.CheckConstraint('initial_balance >= 0', name='ck_leave_balances_initial_positive'),
    sa.CheckConstraint('pending >= 0', name='ck_leave_balances_pending_positive'),
    sa.CheckConstraint('taken >= 0', name='ck_leave_balances_taken_positive'),
    sa.CheckConstraint('year BETWEEN 2000 AND 2100', name='ck_leave_balances_year_valid'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'leave_type_id', 'year', name='uq_leave_balances_employee_type_year')
    )
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.create_index('ix_leave_balances_employee_id', ['employee_id'], unique=False)
        batch_op.create_index('ix_leave_balances_employee_year', ['employee_id', 'year'], unique=False)
        batch_op.create_index('ix_leave_balances_leave_type_id', ['leave_type_id'], unique=False)

    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('start_half_day', sa.Boolean(), nullable=False, comment='Demi-journée le jour de début'),
    sa.Column('end_half_day', sa.Boolean(), nullable=False, comment='Demi-journée le jour de fin'),
    sa.Column('working_days', sa.Numeric(precision=5, scale=2), nullable=True, comment='Jours ouvrés calculés (hors week-ends/fériés) — recalculé par le service'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('employee_comment', sa.Text(), nullable=True),
    sa.Column('document_path', sa.String(length=500), nullable=True, comment='Justificatif joint (arrêt maladie, etc.)'),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('manager_decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manager_comment', sa.Text(), nullable=True),
    sa.Column('hr_user_id', sa.Integer(), nullable=True),
    sa.Column('hr_decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hr_comment', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft','pending_manager','pending_hr','approved','rejected','cancelled')", name='ck_leave_requests_status_valid'),
    sa.CheckConstraint('end_date >= start_date', name='ck_leave_requests_end_after_start'),
    sa.CheckConstraint('manager_decision_at IS NULL OR manager_id IS NOT NULL', name='ck_leave_requests_manager_decision_requires_manager'),
    sa.CheckConstraint('working_days IS NULL OR working_days > 0', name='ck_leave_requests_working_days_positive'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hr_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.create_index('ix_leave_requests_date_range', ['employee_id', 'start_date', 'end_date'], unique=False)
        batch_op.create_index('ix_leave_requests_employee_id', ['employee_id'], unique=False)
        batch_op.create_index('ix_leave_requests_leave_type_id', ['leave_type_id'], unique=False)
        batch_op.create_index('ix_leave_requests_manager_id', ['manager_id'], unique=False)
        batch_op.create_index('ix_leave_requests_pending', ['manager_id', 'status'], unique=False)
        batch_op.create_index('ix_leave_requests_status', ['status'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True, comment='NULL = notification système/automatique'),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True, comment='Lien vers la ressource concernée (deep-link)'),
    sa.Column('entity_type', sa.String(length=80), nullable=True, comment="ex : 'leave_requests', 'evaluations'"),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_error', sa.Text(), nullable=True, comment="Message d'erreur si l'envoi email a échoué"),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Passé cette date, archivage automatique par tâche Celery'),
    sa.CheckConstraint("channel IN ('in_app','email','both')", name='ck_notifications_channel_valid'),
    sa.CheckConstraint("read_at IS NULL OR status IN ('read','archived')", name='ck_notifications_read_consistency'),
    sa.CheckConstraint("status IN ('unread','read','archived')", name='ck_notifications_status_valid'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_notifications_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_notifications_recipient_id', ['recipient_id'], unique=False)
        batch_op.create_index('ix_notifications_recipient_status', ['recipient_id', 'status'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False, comment='SHA-256 du token brut envoyé par email — jamais le token en clair'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('expires_at > created_at', name='ck_prt_expiry_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_prt_user_used', ['user_id', 'used_at'], unique=False)

    op.create_table('public_holidays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True, comment="NULL = s'applique à tous les sites de l'entreprise"),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_national', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'site_id', 'holiday_date', name='uq_public_holidays_company_site_date')
    )
    with op.batch_alter_table('public_holidays', schema=None) as batch_op:
        batch_op.create_index('ix_public_holidays_company_date', ['company_id', 'holiday_date'], unique=False)
        batch_op.create_index('ix_public_holidays_site_id', ['site_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('expires_at > created_at', name='ck_session_expiry_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_session_user_expires', ['user_id', 'expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True, comment='Dénormalisé — conserve la traçabilité même après suppression du compte'),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_uuid', sa.String(length=36), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Contexte additionnel libre (clé-valeur)'),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_action', ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_audit_logs_session_id', ['session_id'], unique=False)
        batch_op.create_index('ix_audit_logs_user_id', ['user_id'], unique=False)
    op.create_foreign_key(
    'fk_employees_site_id_sites',
    'employees', 'sites',
    ['site_id'], ['id'],
    ondelete='SET NULL'
    )
    op.create_foreign_key(
    'fk_employees_user_id_users',
    'employees', 'users',
    ['user_id'], ['id'],
    ondelete='SET NULL'
    )
    op.create_foreign_key(
    'fk_employees_position_id_positions',
    'employees', 'positions',
    ['position_id'], ['id'],
    ondelete='SET NULL'
    )
    op.create_foreign_key(
    'fk_positions_department_id_departments',
    'positions', 'departments',
    ['department_id'], ['id'],
    ondelete='CASCADE'
    )
    op.create_foreign_key(
    'fk_departments_manager_id_employees',
    'departments', 'employees',
    ['manager_id'], ['id'],
    ondelete='SET NULL'
    )
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade():
    op.drop_constraint('fk_departments_manager_id_employees', 'departments', type_='foreignkey')
    op.drop_constraint('fk_positions_department_id_departments', 'positions', type_='foreignkey')
    op.drop_constraint('fk_employees_position_id_positions', 'employees', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_user_id')
        batch_op.drop_index('ix_audit_logs_session_id')
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index('ix_audit_logs_created_at')
        batch_op.drop_index('ix_audit_logs_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index('ix_session_user_expires')

    op.drop_table('user_sessions')
    with op.batch_alter_table('public_holidays', schema=None) as batch_op:
        batch_op.drop_index('ix_public_holidays_site_id')
        batch_op.drop_index('ix_public_holidays_company_date')

    op.drop_table('public_holidays')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_prt_user_used')
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_recipient_status')
        batch_op.drop_index('ix_notifications_recipient_id')
        batch_op.drop_index('ix_notifications_entity')
        batch_op.drop_index('ix_notifications_created_at')

    op.drop_table('notifications')
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_leave_requests_status')
        batch_op.drop_index('ix_leave_requests_pending')
        batch_op.drop_index('ix_leave_requests_manager_id')
        batch_op.drop_index('ix_leave_requests_leave_type_id')
        batch_op.drop_index('ix_leave_requests_employee_id')
        batch_op.drop_index('ix_leave_requests_date_range')

    op.drop_table('leave_requests')
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.drop_index('ix_leave_balances_leave_type_id')
        batch_op.drop_index('ix_leave_balances_employee_year')
        batch_op.drop_index('ix_leave_balances_employee_id')

    op.drop_table('leave_balances')
    with op.batch_alter_table('work_schedules', schema=None) as batch_op:
        batch_op.drop_index('ix_work_schedules_company_id')

    op.drop_table('work_schedules')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_uuid'))
        batch_op.drop_index(batch_op.f('ix_users_role_id'))
        batch_op.drop_index('ix_users_email_lower')
        batch_op.drop_index('ix_users_active')

    op.drop_table('users')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index('ix_sites_company_id')

    op.drop_table('sites')
    op.drop_table('role_permissions')
    with op.batch_alter_table('leave_types', schema=None) as batch_op:
        batch_op.drop_index('ix_leave_types_company_id')
        batch_op.drop_index('ix_leave_types_active')

    op.drop_table('leave_types')
    op.drop_table('roles')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index('ix_positions_level')
        batch_op.drop_index('ix_positions_department_id')

    op.drop_table('positions')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_code'))

    op.drop_table('permissions')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_uuid'))
        batch_op.drop_index('ix_employees_name')
        batch_op.drop_index('ix_employees_manager_id')
        batch_op.drop_index('ix_employees_department_id')
        batch_op.drop_index('ix_employees_company_status')

    op.drop_table('employees')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index('ix_departments_parent_id')
        batch_op.drop_index('ix_departments_manager_id')
        batch_op.drop_index('ix_departments_company_id')

    op.drop_table('departments')
    op.drop_table('companies')
    # ### end Alembic commands ###
