"""add_payslips_pay_elements

Revision ID: de14911a2800
Revises: a1c2d3e4f5a6
Create Date: 2026-06-29 17:41:26.544076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de14911a2800'
down_revision = 'a1c2d3e4f5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payslips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True, comment="Contrat en vigueur au moment de l'émission (snapshot)"),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=False, comment='Salaire brut mensuel (base + éléments variables)'),
    sa.Column('total_employee_contributions', sa.Numeric(precision=12, scale=2), nullable=False, comment='Total des cotisations salariales'),
    sa.Column('total_employer_contributions', sa.Numeric(precision=12, scale=2), nullable=False, comment='Total des cotisations patronales'),
    sa.Column('net_salary', sa.Numeric(precision=12, scale=2), nullable=False, comment='Net à payer = brut − cotisations salariales'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True, comment='Référence virement ou chèque'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft','validated','paid')", name='ck_payslips_status_valid'),
    sa.CheckConstraint('gross_salary > 0', name='ck_payslips_gross_positive'),
    sa.CheckConstraint('net_salary <= gross_salary', name='ck_payslips_net_le_gross'),
    sa.CheckConstraint('net_salary > 0', name='ck_payslips_net_positive'),
    sa.CheckConstraint('period_month BETWEEN 1 AND 12', name='ck_payslips_month_valid'),
    sa.CheckConstraint('period_year >= 2000', name='ck_payslips_year_valid'),
    sa.CheckConstraint('total_employee_contributions >= 0', name='ck_payslips_employee_contributions_positive'),
    sa.CheckConstraint('total_employer_contributions >= 0', name='ck_payslips_employer_contributions_positive'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'period_year', 'period_month', name='uq_payslips_employee_period')
    )
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.create_index('ix_payslips_employee_id', ['employee_id'], unique=False)
        batch_op.create_index('ix_payslips_period', ['period_year', 'period_month'], unique=False)
        batch_op.create_index('ix_payslips_status', ['status'], unique=False)

    op.create_table('pay_elements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payslip_id', sa.Integer(), nullable=False),
    sa.Column('element_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False, comment="Libellé affiché sur le bulletin (ex: 'Prime d'ancienneté', 'URSSAF maladie')"),
    sa.Column('is_employer', sa.Boolean(), nullable=False, comment='True = cotisation patronale ; False = salariale ou élément standard'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Montant toujours positif ; le sens est déterminé par element_type'),
    sa.Column('rate', sa.Numeric(precision=6, scale=4), nullable=True, comment='Taux appliqué en % (ex: 22.0000 pour 22 %)'),
    sa.Column('base_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Assiette sur laquelle le taux est calculé'),
    sa.CheckConstraint("element_type IN ('bonus','deduction','contribution')", name='ck_pay_elements_type_valid'),
    sa.CheckConstraint('amount > 0', name='ck_pay_elements_amount_positive'),
    sa.CheckConstraint('base_amount IS NULL OR base_amount > 0', name='ck_pay_elements_base_positive'),
    sa.CheckConstraint('rate IS NULL OR (rate > 0 AND rate <= 100)', name='ck_pay_elements_rate_valid'),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pay_elements', schema=None) as batch_op:
        batch_op.create_index('ix_pay_elements_payslip_id', ['payslip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pay_elements', schema=None) as batch_op:
        batch_op.drop_index('ix_pay_elements_payslip_id')

    op.drop_table('pay_elements')
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.drop_index('ix_payslips_status')
        batch_op.drop_index('ix_payslips_period')
        batch_op.drop_index('ix_payslips_employee_id')

    op.drop_table('payslips')
    # ### end Alembic commands ###
