"""add avatar_path to users

Revision ID: f7331b8d5cf3
Revises: 75608117b219
Create Date: 2026-07-01 12:21:56.683709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7331b8d5cf3'
down_revision = '75608117b219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_path', sa.String(length=500), nullable=True, comment='Chemin relatif depuis UPLOAD_FOLDER — pas de donnée sensible, non chiffré'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_path')

    # ### end Alembic commands ###
