"""encrypt sensitive employee fields

Revision ID: fd115f7e3b87
Revises: 0b9fe28e7e3b
Create Date: 2026-06-29 00:23:31.843223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd115f7e3b87'
down_revision = '0b9fe28e7e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('national_id_number',
               existing_type=sa.VARCHAR(length=255),
               comment='Numéro de sécurité sociale — CHIFFRÉ Fernet avant stockage',
               existing_comment='Numéro de sécurité sociale — CHIFFRÉ côté application avant stockage',
               existing_nullable=True)
        batch_op.alter_column('iban',
               existing_type=sa.VARCHAR(length=255),
               comment='IBAN — CHIFFRÉ Fernet avant stockage',
               existing_comment='Chiffré côté application (AES-256)',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('iban',
               existing_type=sa.VARCHAR(length=255),
               comment='Chiffré côté application (AES-256)',
               existing_comment='IBAN — CHIFFRÉ Fernet avant stockage',
               existing_nullable=True)
        batch_op.alter_column('national_id_number',
               existing_type=sa.VARCHAR(length=255),
               comment='Numéro de sécurité sociale — CHIFFRÉ côté application avant stockage',
               existing_comment='Numéro de sécurité sociale — CHIFFRÉ Fernet avant stockage',
               existing_nullable=True)

    # ### end Alembic commands ###
